python test.py \
--gpu_ids 3 \
--dataroot /data/baole/dbs_zhongnan/unaligned \
--results_dir ./results/after_compare \
--name dbs \
--model ant_gan \
--dataset unaligned \
--checkpoints_dir checkpoints_compare \
--direction AtoB \
--load_size 512 \
--crop_size 512 \
--batch_size 16 \
--suffix {model}_{netG}_{n_downsampling}_{netD}_{n_layers_D}_size_{load_size} \
--netG resnet_12blocks \
--n_downsampling 3 \
--netD n_layers \
--n_layers_D 4 \
--epoch best \
--lambda_identity 0 \
--lambda_mask 10000 \
--diff_A fake_B \
--diff_B real_A \
--diff \
--serial_batches \
--no_flip