python test.py \
--gpu_ids 0 \
--dataroot /data/baole/dbs_zhongnan/aligned_ring \
--results_dir ./results/experiments \
--name dbs \
--model ant_gan_duel_patch \
--dataset masked \
--direction AtoB \
--load_size 512 \
--crop_size 512 \
--batch_size 16 \
--suffix {model}_{netG}_size_{load_size} \
--netG resnet_9blocks \
--netD n_layers \
--epoch best \
--lambda_identity 0 \
--lambda_mask 500 \
--checkpoints_dir experiments \
--diff_A fake_B \
--diff_B real_A \
--metrics \
--serial_batches \
--diff \
--no_flip