nohup python train.py \
--gpu_ids 2 \
--name dbs \
--model ant_gan \
--dataset masked \
--checkpoints_dir checkpoints_compare \
--dataroot /data/baole/dbs_zhongnan/unaligned \
--direction AtoB \
--load_size 512 \
--crop_size 512 \
--display_port 1235 \
--batch_size 2 \
--suffix {model}_{netG}_{n_downsampling}_{netD}_{n_layers_D}_size_{load_size} \
--display_freq -1 \
--print_freq -1 \
--save_epoch_freq -1 \
--netG resnet_9blocks \
--n_downsampling 3 \
--netD n_layers \
--n_layers_D 4 \
--n_epochs 100 \
--n_epochs_decay 100 \
--patience -1 \
--lambda_identity 0 \
--lambda_mask 10000 \
--no_flip \
> logs/train_ant_gan_28.log 2>&1 &