nohup python train.py \
--gpu_ids 1 \
--name dbs \
--model vgg16 \
--dataroot /data/baole/dbs_zhongnan/unaligned \
--dataset vgg \
--direction AtoB \
--load_size 512 \
--crop_size 224 \
--display_port 1233 \
--batch_size 128 \
--lr 0.0001 \
--suffix {model}_size_{crop_size}_test \
--display_freq -1 \
--print_freq -1 \
--netG resnet_9blocks \
--netD n_layers \
--n_epochs 100 \
--n_epochs_decay 100 \
--patience -1 \
--no_flip \
> logs/train_vgg16_small_test.log 2>&1 &